name: base
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - anaconda-anon-usage=0.4.4=py312hfc0e8ea_100
  - archspec=0.2.3=pyhd3eb1b0_0
  - boltons=23.0.0=py312h06a4308_0
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2024.3.11=h06a4308_0
  - cffi=1.16.0=py312h5eee18b_1
  - conda=24.4.0=py312h06a4308_0
  - conda-content-trust=0.2.0=py312h06a4308_1
  - conda-libmamba-solver=24.1.0=pyhd3eb1b0_0
  - conda-package-handling=2.2.0=py312h06a4308_1
  - conda-package-streaming=0.9.0=py312h06a4308_0
  - cryptography=42.0.5=py312hdda0065_1
  - distro=1.9.0=py312h06a4308_0
  - expat=2.6.2=h6a678d5_0
  - fmt=9.1.0=hdb19cb5_1
  - icu=73.1=h6a678d5_0
  - jsonpatch=1.33=py312h06a4308_1
  - jsonpointer=2.1=pyhd3eb1b0_0
  - krb5=1.20.1=h143b758_1
  - ld_impl_linux-64=2.38=h1181459_1
  - libarchive=3.6.2=h6ac8c49_3
  - libcurl=8.7.1=h251f7ec_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libmamba=1.5.8=hfe524e5_2
  - libmambapy=1.5.8=py312h2dafd23_2
  - libnghttp2=1.57.0=h2d74bed_0
  - libsolv=0.7.24=he621ea3_1
  - libssh2=1.11.0=h251f7ec_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxml2=2.10.4=hfdd30dd_2
  - lz4-c=1.9.4=h6a678d5_1
  - menuinst=2.0.2=py312h06a4308_1
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.13=h7f8727e_1
  - pcre2=10.42=hebb0a14_1
  - pip=24.0=py312h06a4308_0
  - platformdirs=3.10.0=py312h06a4308_0
  - pluggy=1.0.0=py312h06a4308_1
  - pybind11-abi=5=hd3eb1b0_0
  - pycosat=0.6.6=py312h5eee18b_1
  - pycparser=2.21=pyhd3eb1b0_0
  - pysocks=1.7.1=py312h06a4308_0
  - python=3.12.3=h996f2a0_1
  - readline=8.2=h5eee18b_0
  - reproc=14.2.4=h6a678d5_2
  - reproc-cpp=14.2.4=h6a678d5_2
  - ruamel.yaml=0.17.21=py312h5eee18b_0
  - setuptools=69.5.1=py312h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - truststore=0.8.0=py312h06a4308_0
  - wheel=0.43.0=py312h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - yaml-cpp=0.8.0=h6a678d5_1
  - zlib=1.2.13=h5eee18b_1
  - zstandard=0.22.0=py312h2c38b39_0
  - zstd=1.5.5=hc292b87_2
  - pip:
      - absl-py==2.3.1
      - accelerate==1.12.0
      - aiofiles==24.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anyio==4.10.0
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.3.0
      - asttokens==3.0.0
      - async-lru==2.0.5
      - attrs==25.3.0
      - babel==2.17.0
      - beautifulsoup4==4.13.4
      - bleach==6.2.0
      - brotli==1.2.0
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - clean-fid==0.1.35
      - click==8.3.1
      - clip==1.0
      - comm==0.2.3
      - contourpy==1.3.3
      - cycler==0.12.1
      - datasets==4.4.1
      - debugpy==1.8.16
      - decorator==5.2.1
      - deep-translator==1.11.4
      - defusedxml==0.7.1
      - diffusers==0.36.0.dev0
      - dill==0.4.0
      - executing==2.2.0
      - fastapi==0.128.0
      - fastjsonschema==2.21.1
      - ffmpy==1.0.0
      - filelock==3.20.1
      - fonttools==4.59.0
      - fqdn==1.5.1
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - ftfy==6.3.1
      - gitdb==4.0.12
      - gitpython==3.1.45
      - gradio==6.2.0
      - gradio-client==2.0.2
      - groovy==0.1.2
      - grpcio==1.74.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - idna==3.11
      - importlib-metadata==8.7.0
      - ipykernel==6.30.1
      - ipython==9.4.0
      - ipython-pygments-lexers==1.1.1
      - ipywidgets==8.1.7
      - isoduration==20.11.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - json5==0.12.0
      - jsonschema==4.25.0
      - jsonschema-specifications==2025.4.1
      - jupyter-client==8.6.3
      - jupyter-core==5.8.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.2.6
      - jupyter-server==2.16.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.5
      - jupyterlab-language-pack-zh-cn==4.4.post0
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.15
      - kiwisolver==1.4.8
      - lark==1.2.2
      - lightning-utilities==0.15.2
      - markdown==3.8.2
      - markdown-it-py==4.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.5
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mistune==3.1.3
      - modelscope==1.33.0
      - mpmath==1.3.0
      - multidict==6.7.0
      - multiprocess==0.70.18
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.5
      - notebook-shim==0.2.4
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.8.90
      - open-clip-torch==3.2.0
      - opencv-python==4.12.0.88
      - orjson==3.11.5
      - overrides==7.7.0
      - packaging==25.0
      - pandas==2.3.3
      - pandocfilters==1.5.1
      - parso==0.8.4
      - peft==0.18.0
      - pexpect==4.9.0
      - pillow==11.3.0
      - polars==1.36.1
      - polars-runtime-32==1.36.1
      - prometheus-client==0.22.1
      - prompt-toolkit==3.0.51
      - propcache==0.4.1
      - protobuf==6.31.1
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==22.0.0
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pydub==0.25.1
      - pygments==2.19.2
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - python-json-logger==3.3.0
      - python-multipart==0.0.21
      - pytz==2025.2
      - pyyaml==6.0.3
      - pyzmq==27.0.1
      - referencing==0.36.2
      - regex==2025.11.3
      - requests==2.32.5
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rich==14.2.0
      - rpds-py==0.26.0
      - safehttpx==0.1.7
      - safetensors==0.7.0
      - scipy==1.16.3
      - segment-anything==1.0
      - semantic-version==2.10.0
      - send2trash==1.8.3
      - sentencepiece==0.2.1
      - sentry-sdk==2.48.0
      - shellingham==1.5.4
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - soupsieve==2.7
      - stack-data==0.6.3
      - starlette==0.50.0
      - supervisor==4.2.5
      - sympy==1.14.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - terminado==0.18.1
      - timm==1.0.22
      - tinycss2==1.4.0
      - tokenizers==0.22.1
      - tomlkit==0.13.3
      - torch==2.9.1
      - torch-fidelity==0.3.0
      - torchmetrics==1.8.2
      - torchvision==0.24.1
      - tornado==6.5.1
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.57.3
      - triton==3.5.1
      - typer==0.21.0
      - typer-slim==0.20.0
      - types-python-dateutil==2.9.0.20250708
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - ultralytics==8.3.240
      - ultralytics-thop==2.0.18
      - uri-template==1.3.0
      - urllib3==2.6.2
      - uvicorn==0.40.0
      - wandb==0.23.1
      - wcwidth==0.2.13
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - werkzeug==3.1.3
      - widgetsnbextension==4.0.14
      - xformers==0.0.33.post2
      - xxhash==3.6.0
      - yarl==1.22.0
      - zipp==3.23.0
prefix: /root/miniconda3
